Traceback (most recent call last):
  File "C:\Users\masonl\AppData\Local\anaconda3\envs\jbookr\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\masonl\AppData\Local\anaconda3\envs\jbookr\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\masonl\AppData\Local\anaconda3\envs\jbookr\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\masonl\AppData\Local\anaconda3\envs\jbookr\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\masonl\AppData\Local\anaconda3\envs\jbookr\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\masonl\AppData\Local\anaconda3\envs\jbookr\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\masonl\AppData\Local\anaconda3\envs\jbookr\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\masonl\AppData\Local\anaconda3\envs\jbookr\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
polys <- st_read('voronoi.kml')
------------------

Error: Cannot open "voronoi.kml"; The file doesn't seem to exist.
Traceback:

1. st_read("voronoi.kml")
2. st_read.character("voronoi.kml")
3. CPL_read_ogr(dsn, layer, query, as.character(options), quiet, 
 .     type, fid_column_name, drivers, wkt_filter, promote_to_multi, 
 .     int64_as_string, dsn_exists, dsn_isdb, getOption("width"))
ERROR: Error: Cannot open "voronoi.kml"; The file doesn't seem to exist.


